language: python
python: 2.7
install:
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg -N -q
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bin/code-analysis
- bin/test
after_success:
- bin/coverage.sh
- pip install -q coveralls
- coveralls
after_failure:
- bin/buildout annotate -c travis.cfg
- firefox -v